version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/var/www/html
    restart: unless-stopped
    networks:
      - laravel
    ports:
      - "80:80"
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: unless-stopped
    container_name: db
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./laravel.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel
    restart: always 
    container_name: nginx

volumes:
  dbdata:

networks:
  laravel:
    driver: bridge
    